name: Deploy FastAPI App to Uberspace

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.30"

      # Step 3: Set up Python
      - name: Set up Python
        run: uv python install

      # Step 4: Install the FastAPI app dependencies
      - name: Install FastAPI app dependencies
        run: uv sync --frozen --no-cache

      # Step 5: Deploy to Uberspace using Rsync
      - name: Deploy FastAPI app to Uberspace
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete
          path: /
          remote_path: /var/www/virtual/${{ vars.SSH_USERNAME }}/html
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 6: Restart FastAPI Application
      - name: Restart FastAPI Application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "supervisorctl restart fastapi"
