name: Example

on:
    push:
      branches: [ main ]

env:
  UBERSPACE_HOST: ${{ secrets.UBERSPACE_HOST }}
  UBERSPACE_USER: ${{ secrets.UBERSPACE_USER }}
  APP_DIR: ~/fastapi_app

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev
